export enum Brevtype {
  INNVILGELSE = 'INNVILGELSE',
  AVSLAG = 'AVSLAG',
  VARSEL_OM_BESTILLING = 'VARSEL_OM_BESTILLING',
  FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT = 'FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT',
  FORVALTNINGSMELDING = 'FORVALTNINGSMELDING',
  VEDTAK_ENDRING = 'VEDTAK_ENDRING',
  KLAGE_AVVIST = 'KLAGE_AVVIST',
  KLAGE_OPPRETTHOLDELSE = 'KLAGE_OPPRETTHOLDELSE',
  KLAGE_TRUKKET = 'KLAGE_TRUKKET',
}
