export enum Brevtype {
  INNVILGELSE = 'INNVILGELSE',
  AVSLAG = 'AVSLAG',
  VARSEL_OM_BESTILLING = 'VARSEL_OM_BESTILLING',
  FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT = 'FORHÅNDSVARSEL_BRUDD_AKTIVITETSPLIKT',
  FORVALTNINGSMELDING = 'FORVALTNINGSMELDING',
}
